wip: platform-mc: terminus_manager: Remove unused event field
```
In file included from ../platform-mc/terminus_manager.cpp:1:
../platform-mc/terminus_manager.hpp:211:25: error: private field 'event' is not used [-Werror,-Wunused-private-field]
  211 |     sdeventplus::Event& event;
      |                         ^
```

Change-Id: Ibcad959ae4c0272aa2f923ca8c5fa3ee292b06e2
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>