wip: libpldmresponder: bios_config: Remove unused 'fd'
```
../libpldmresponder/bios_config.hpp:164:9: error: private field 'fd' is not used [-Werror,-Wunused-private-field]
  164 |     int fd;
      |         ^
```

Change-Id: If4aeb134726fe7bfb2c884c4c4854337a93318bb
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>