wip: oem-ibm: libpldmresponder: file_io: Remove unused initialisers
```
In file included from ../oem/ibm/libpldmresponder/file_io.cpp:1:
../oem/ibm/libpldmresponder/file_io.hpp:173:9: error: member initializer 'hostSockFd' does not name a non-static data member or base class
  173 |         hostSockFd(hostSockFd), hostEid(hostEid), instanceIdDb(instanceIdDb),
      |         ^~~~~~~~~~~~~~~~~~~~~~
../oem/ibm/libpldmresponder/file_io.hpp:173:33: error: member initializer 'hostEid' does not name a non-static data member or base class
  173 |         hostSockFd(hostSockFd), hostEid(hostEid), instanceIdDb(instanceIdDb),
      |                                 ^~~~~~~~~~~~~~~~
../oem/ibm/libpldmresponder/file_io.hpp:173:51: error: member initializer 'instanceIdDb' does not name a non-static data member or base class
  173 |         hostSockFd(hostSockFd), hostEid(hostEid), instanceIdDb(instanceIdDb),
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
../oem/ibm/libpldmresponder/file_io.hpp:174:9: error: member initializer 'handler' does not name a non-static data member or base class
  174 |         handler(handler)
      |         ^~~~~~~~~~~~~~~~
```

Change-Id: I79927d80e9ac48c1089162a98053ff154216d095
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>