wip: host-bmc: dbus_to_event_handler: Elide name of unused mctp_fd parameter
```
../host-bmc/dbus_to_event_handler.cpp:22:9: error: unused parameter 'mctp_fd' [-Werror,-Wunused-parameter]
   22 |     int mctp_fd, uint8_t mctp_eid, pldm::InstanceIdDb& instanceIdDb,
      |         ^
```

Change-Id: Ia4bd0919bc5075a22906cd5aeb6c28d462920d39
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>