wip: oem-ibm: libpldmresponder: file_io: Remove unused instanceIdDb
```
../oem/ibm/libpldmresponder/file_io.hpp:420:25: error: private field 'instanceIdDb' is not used [-Werror,-Wunused-private-field]
  420 |     pldm::InstanceIdDb* instanceIdDb;
      |                         ^
```

Change-Id: Iece04851edfb9a6c2c27b2e270a8d5e24d6d0c6e
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>