wip: host-bmc: host_pdr_handler: Drop unused fruJson
```
../host-bmc/host_pdr_handler.cpp:33:16: error: unused variable 'fruJson' [-Werror,-Wunused-const-variable]
   33 | constexpr auto fruJson = "host_frus.json";
      |                ^~~~~~~
```

Change-Id: Ia04cb6beba4465fa0fa872b84c5b58f05c90ca36
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>