wip: oem-ibm: libpldmresponder: file_io: Remove unused hostSockFd
```
../oem/ibm/libpldmresponder/file_io.hpp:418:9: error: private field 'hostSockFd' is not used [-Werror,-Wunused-private-field]
  418 |     int hostSockFd;
      |         ^
```

Change-Id: Ifd2e813423b7bc0bd67780c0fc21e32cf8de3e85
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>