wip: oem-ibm: libpldmresponder: file_io: Remove unused hostEid
```
../oem/ibm/libpldmresponder/file_io.hpp:419:13: error: private field 'hostEid' is not used [-Werror,-Wunused-private-field]
  419 |     uint8_t hostEid;
      |             ^
```

Change-Id: I5dfca15f8d092b4355644506e45725261e68285e
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>