wip: platform-mc: terminus_manager: Elide name of unused parameter event
```
../platform-mc/terminus_manager.hpp:54:50: error: unused parameter 'event' [-Werror,-Wunused-parameter]
   54 |     explicit TerminusManager(sdeventplus::Event& event,
      |                                                  ^
```

Change-Id: Ia73554cab86a06ac73d89a0af9825aab04303d8d
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>