wip: libpldmresponder: bios_config: Elide name for unused fd parameter
```
../libpldmresponder/bios_config.cpp:44:9: error: unused parameter 'fd' [-Werror,-Wunused-parameter]
   44 |     int fd, uint8_t eid, pldm::InstanceIdDb* instanceIdDb,
      |         ^
```

Change-Id: Ied81e64e741a28c15df3d3a2378a746d441e49bf
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>