wip: pldmd: Remove unused MCTP_MSG_TYPE_PLDM
```
../pldmd/pldmd.cpp:67:19: error: unused variable 'MCTP_MSG_TYPE_PLDM' [-Werror,-Wunused-const-variable]
   67 | constexpr uint8_t MCTP_MSG_TYPE_PLDM = 1;
      |                   ^~~~~~~~~~~~~~~~~~
```

Change-Id: I12724e6639ad359b9b8cba4cf523ce86b8bd6d24
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>