wip: host-bmc: host_pdr_handler: Remove unused mctp_fd member
```
../host-bmc/host_pdr_handler.hpp:277:9: error: private field 'mctp_fd' is not used [-Werror,-Wunused-private-field]
  277 |     int mctp_fd;
      |         ^
```

Change-Id: Icc32ec16ca3a0c714d18df8f576bad75137e1a19
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>