wip: host-bmc: host_pdr_handler: Remove unused bmcEntityTree field
```
../host-bmc/host_pdr_handler.hpp:292:35: error: private field 'bmcEntityTree' is not used [-Werror,-Wunused-private-field]
  292 |     pldm_entity_association_tree* bmcEntityTree;
      |                                   ^
```

Change-Id: I62a948dff51b184bf44f1053b48d3b512e3e2b72
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>