wip: oem-ibm: libpldmresponder: file_io_type_vpd: Remove unused vpdFileType
```
In file included from ../oem/ibm/libpldmresponder/file_io_type_vpd.cpp:1:
../oem/ibm/libpldmresponder/file_io_type_vpd.hpp:72:14: error: private field 'vpdFileType' is not used [-Werror,-Wunused-private-field]
   72 |     uint16_t vpdFileType; //!< type of the VPD file
      |              ^
```

Change-Id: If1208f21bcedaff912079371cf2e79df4b17093f
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>