wip: oem-ibm: libpldmresponder: file_io_type_vpd: Elide unused fileType
```
../oem/ibm/libpldmresponder/file_io_type_vpd.hpp:20:50: error: unused parameter 'fileType' [-Werror,-Wunused-parameter]
   20 |     keywordHandler(uint32_t fileHandle, uint16_t fileType) :
      |                                                  ^
```

Change-Id: I6c2e0c519323117513603f878ea850db9344823f
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>